# Generated by Django 4.2.16 on 2024-11-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='genre',
            field=models.CharField(max_length=30, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
    ]
