# Generated by Django 4.2.16 on 2024-11-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_playlist_genre_alter_playlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='desc',
            field=models.CharField(default='', max_length=300, verbose_name='Desc'),
        ),
    ]
