# Generated by Django 4.2.16 on 2024-11-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_playlist_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='desc',
            field=models.CharField(default='', max_length=600, verbose_name='Desc'),
        ),
    ]
